version: 1.0.{build}
image: Visual Studio 2017
configuration:
  - Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack GeneGenie.Gedcom\GeneGenie.Gedcom.csproj --configuration Release --output . --no-build
artifacts:
- path: '**/*.nupkg'
  name: nugetpackage
deploy:
- provider: NuGet
  api_key:
    secure: P8cmu7BZh3GOr+3bq5NVZEAEGnvjyC1wKhEmk4pcfTxiZwP7qS2t0pTPPn+q4ILC
  artifact: nugetpackage
  on:
    branch: master

test_script:
 - dotnet test GeneGenie.Gedcom.Tests/GeneGenie.Gedcom.Tests.csproj
after_test:
  - cmd: SonarQube.bat
