version: 1.0.{build}
image: Visual Studio 2017
configuration:
  - Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack GeneGenie.Gedcom\GeneGenie.Gedcom.csproj --configuration Release --output . --no-build
artifacts:
- path: '**/*.nupkg'
  name: nugetpackage
deploy:
- provider: NuGet
  api_key:
    secure: bcYrYC8tAmSYcblYfwjk9upKKLg6kEuQbYVAw9knvBSu32OOfmtXPXHwpDqSCadQ
  artifact: nugetpackage
  on:
    branch: master

test_script:
  - cmd: SonarQube.bat
